import requests

url = "https://api.strata.paloaltonetworks.com/sse/config/v1/mobile-agent/infrastructure-settings?folder=Mobile%20Users"

payload = {}
headers = {
  'Accept': 'application/json',
  'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJraWQiOiJyc2Etc2lnbi1wa2NzMS0yMDQ4LXNoYTI1Ni8xIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJhMzlkN2M3OS1hMDQwLTRiZGEtYjYxZC1jNGI4M2YyMDFiOTkiLCJjdHMiOiJPQVVUSDJfU1RBVEVMRVNTX0dSQU5UIiwiYXVkaXRUcmFja2luZ0lkIjoiMTJlNDAzYTYtYWIyZC00OTllLTllOWMtZmE0ZmIwZjY4MThmLTEwNzA4NDUwMjciLCJzdWJuYW1lIjoiYTM5ZDdjNzktYTA0MC00YmRhLWI2MWQtYzRiODNmMjAxYjk5IiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmFwcHMucGFsb2FsdG9uZXR3b3Jrcy5jb206NDQzL2FtL29hdXRoMiIsInRva2VuTmFtZSI6ImFjY2Vzc190b2tlbiIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJhdXRoR3JhbnRJZCI6IjhBb3dXT1RBdjBUSG9FVXhUaVNzV2xxaHo5RSIsImF1ZCI6Im1yZWN0b3Itc2VydmljZS1hY2NvdW50QDE2MDI0MzYxODYuaWFtLnBhbnNlcnZpY2VhY2NvdW50LmNvbSIsIm5iZiI6MTc4NDY1ODI0MywiZ3JhbnRfdHlwZSI6ImNsaWVudF9jcmVkZW50aWFscyIsInNjb3BlIjpbInRzZ19pZDoxOTQ3OTg1MzgzIiwicHJvZmlsZSIsImVtYWlsIl0sImF1dGhfdGltZSI6MTc4NDY1ODI0MywicmVhbG0iOiIvIiwiZXhwIjoxNzg0NjU5MTQzLCJpYXQiOjE3ODQ2NTgyNDMsImV4cGlyZXNfaW4iOjkwMCwianRpIjoiMDVFQVUyQy1LdHVpaVBEZ2VOem9PcVFYM0M0IiwidHNnX2lkIjoiMTk0Nzk4NTM4MyIsImFjY2VzcyI6eyJwcm46MTk0Nzk4NTM4Mzo6OjoiOlsic3VwZXJ1c2VyIiwiYmFzZSJdfX0.au1NWdE7sDYSUuLlkJiFYHpn_6wsYJAv3RN2LzfGcVs2zhoTOdq8LJdzbjLHCe6qRMaUv-QsKHsQMOz2ZI6sFOyhPrWxneGrlaARoJYZ0iIAS-V_o8YHhqhWOU0_m5dbKjs4DYKJhN6GsJVGDeur-WF7llHBivXIQICQMjLETHeXaDboEFYBkoIr6xXdTFBwY9tvw0mmEPQ9N9OQ8CakB0XnfdrcnQ7JXmuAnDjkM8TBXRimjaHVzdGbanimnBKYavfepjgGC4LlA3YmOJBZL6V4hRFTk85akWhkLTkRsEwFzykCSa9xFd-yZiRZR6WzZgoNsNzNiZbS8OJ6MlTn3g'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)