import requests

url = "https://api.strata.paloaltonetworks.com/config/mobile-agent/v1/agent-profiles?folder=Mobile Users"

payload = {}
headers = {
  'Accept': 'application/json',
  'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJraWQiOiJyc2Etc2lnbi1wa2NzMS0yMDQ4LXNoYTI1Ni8xIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJhMzlkN2M3OS1hMDQwLTRiZGEtYjYxZC1jNGI4M2YyMDFiOTkiLCJjdHMiOiJPQVVUSDJfU1RBVEVMRVNTX0dSQU5UIiwiYXVkaXRUcmFja2luZ0lkIjoiMTJlNDAzYTYtYWIyZC00OTllLTllOWMtZmE0ZmIwZjY4MThmLTQzOTUwNjA2NCIsInN1Ym5hbWUiOiJhMzlkN2M3OS1hMDQwLTRiZGEtYjYxZC1jNGI4M2YyMDFiOTkiLCJpc3MiOiJodHRwczovL2F1dGguYXBwcy5wYWxvYWx0b25ldHdvcmtzLmNvbTo0NDMvYW0vb2F1dGgyIiwidG9rZW5OYW1lIjoiYWNjZXNzX3Rva2VuIiwidG9rZW5fdHlwZSI6IkJlYXJlciIsImF1dGhHcmFudElkIjoibkx0Z2dPMGxjVXlEeFNBSzh0Y2RyQWY2b21jIiwiYXVkIjoibXJlY3Rvci1zZXJ2aWNlLWFjY291bnRAMTYwMjQzNjE4Ni5pYW0ucGFuc2VydmljZWFjY291bnQuY29tIiwibmJmIjoxNzgyMzExNzYwLCJncmFudF90eXBlIjoiY2xpZW50X2NyZWRlbnRpYWxzIiwic2NvcGUiOlsicHJvZmlsZSIsInRzZ19pZDoxNDA5OTUxNjY0IiwiZW1haWwiXSwiYXV0aF90aW1lIjoxNzgyMzExNzYwLCJyZWFsbSI6Ii8iLCJleHAiOjE3ODIzMTI2NjAsImlhdCI6MTc4MjMxMTc2MCwiZXhwaXJlc19pbiI6OTAwLCJqdGkiOiJxdzlkclFoYy1JWGJkTGJobmhZY2FhUEd3SE0iLCJ0c2dfaWQiOiIxNDA5OTUxNjY0IiwiYWNjZXNzIjp7InBybjoxNDA5OTUxNjY0Ojo6OiI6WyJzdXBlcnVzZXIiLCJiYXNlIl19fQ.S-oMBGRXYYvvN_tNMRNXauw0MXZRu7PnE6cSH0YGNZaZa5hjyTQdoM1FtzgBflU06cv2T5eeFP-xmA57Z06Du6SMBOa8MzZNLzEZZIjYuGeUcJPzkkvccNdSnXTc_MReKh2tmLM-2ZVNEcU_HTZpEZEMPNZeiblw46c5JPOg-qDg9nb1HHlFcAWdWL_FhdKKSNUnwX2bUePqBQVC0q2A_MMd8MDHq32WKgW5D-cMSAbUSRoIiXPW6Z86hu0Ow5K6afRrAe1DR3BBlu7TDyFJxoEYzrnqUnOv66RkehrOozbMgCNCVAddOSjh8wpLbnJhxat1GEJpPZoDFeURTMg2NQ'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)