import requests

url = "https://api.strata.paloaltonetworks.com/config/mobile-agent/v1/locations?folder=Mobile Users"

payload = {}
headers = {
  'Accept': 'application/json',
  'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJraWQiOiJyc2Etc2lnbi1wa2NzMS0yMDQ4LXNoYTI1Ni8xIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJhMzlkN2M3OS1hMDQwLTRiZGEtYjYxZC1jNGI4M2YyMDFiOTkiLCJjdHMiOiJPQVVUSDJfU1RBVEVMRVNTX0dSQU5UIiwiYXVkaXRUcmFja2luZ0lkIjoiMmRhYmI4NDQtZGRmNC00ODI2LTlkOTctZGU4ZDBjODU5NmI5LTIyNDAyMDg0MCIsInN1Ym5hbWUiOiJhMzlkN2M3OS1hMDQwLTRiZGEtYjYxZC1jNGI4M2YyMDFiOTkiLCJpc3MiOiJodHRwczovL2F1dGguYXBwcy5wYWxvYWx0b25ldHdvcmtzLmNvbTo0NDMvYW0vb2F1dGgyIiwidG9rZW5OYW1lIjoiYWNjZXNzX3Rva2VuIiwidG9rZW5fdHlwZSI6IkJlYXJlciIsImF1dGhHcmFudElkIjoiVlpxTTV6ZzBhbHlqM0l5TFJZeWx0TUJ1RkJZIiwiYXVkIjoibXJlY3Rvci1zZXJ2aWNlLWFjY291bnRAMTYwMjQzNjE4Ni5pYW0ucGFuc2VydmljZWFjY291bnQuY29tIiwibmJmIjoxNzgwNDIzMTU3LCJncmFudF90eXBlIjoiY2xpZW50X2NyZWRlbnRpYWxzIiwic2NvcGUiOlsidHNnX2lkOjE5NDc5ODUzODMiLCJwcm9maWxlIiwiZW1haWwiXSwiYXV0aF90aW1lIjoxNzgwNDIzMTU3LCJyZWFsbSI6Ii8iLCJleHAiOjE3ODA0MjQwNTcsImlhdCI6MTc4MDQyMzE1NywiZXhwaXJlc19pbiI6OTAwLCJqdGkiOiJ1NXBEcEFGSExLeWVkMmViUkZyUDNDU1J4TjAiLCJ0c2dfaWQiOiIxOTQ3OTg1MzgzIiwiYWNjZXNzIjp7InBybjoxOTQ3OTg1MzgzOjo6OiI6WyJzdXBlcnVzZXIiLCJiYXNlIl19fQ.ibNCGc2m7xAIb_qkV7siXXoyizKb3zMxsOlzLSPrHV9A11m1Qhz-rrSpU-i4fB5tZiEsrvSq8tgm3Eh4fqsr-3icKLZMrD4-MAh1KZpruRGZ6ZkA2vm4I83pxLOwHed9xSIIMZqWqDoat3NCqEDol9Di40gJZ4a1PUzllEkVlzARQ8_wH3ZlghBKFGW_eA0RCq1FvmTr7YDzLDbmTJX_k3CXMNclNYgO8zMJ4BtXmf2Wr5AJQu2w38ouR_yLhRbxNBHEh_tHbl6LDDiskPRY5pRO_SeCmJjVrKwYsbkeU8keg4ULeRxdNYKeYOviPfL2-gq0atLoFsprTtUeHH6gPw'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)